#Config
# These must be between 10 and -10, however you might want to limit the speed more than that, as 10 is extremely fast
# and may allow people to lag your server by generating too many chunks too quickly
"max-fly-speed": 8.0
"min-fly-speed": -8.0
# Where should flight persist? (flight won't disable due to these events)
"session-persistent-flight" : true
"world-change-persistent-flight" : true
"respawn-persistent-flight" : true
"gamemode-change-persistent-flight" : true
